Name: preview-eventtemple
DockerImage: "{{IMAGE}}"
Replicas: 1
Cloud: 0
IsLBSyncedDeployment: true
AgentPlatform: 7
OtherDockerConfig: |
  {
    "EnvFrom": [
      {
        "secretRef": {
          "name": "preview-eventtemple"
        }
      }
    ],
    "Command": [
      "bin/start-nginx",
      "bundle",
      "exec",
      "puma",
      "-C",
      "config/puma.rb"
    ]
  }
NetworkId: default
