Name: preview-eventtemple
DockerImage: "{{IMAGE}}"
Replicas: 1
Cloud: 0
IsLBSyncedDeployment: true
AgentPlatform: 7
env:
  - name: REDIS
    value: preview-redis
OtherDockerConfig: |
  {
    "EnvFrom": [
      {
        "secretRef": {
          "name": "preview-eventtemple"
        }
      },
      "Env": [
      { "name": "REDIS", "value": "preview-redis" }
    ],
    "Command": [
      "bin/start-nginx",
      "bundle",
      "exec",
      "puma",
      "-C",
      "config/puma.rb"
    ]
  }
NetworkId: default
