Name: eventtemple
DockerImage: "{{IMAGE}}"
Replicas: 1
Cloud: 0
IsLBSyncedDeployment: true
AgentPlatform: 7
otherPodConfig:
  envFrom:
    - secretRef:
        name: eventtemple
  command:
    - bin/start-nginx
    - bundle
    - exec
    - puma
    - -C
    - config/puma.rb
NetworkId: default
