Name: preview-redis-lb
Tenant: stage
Protocol: tcp
Port: 6379
TargetPort: 6379
IsNative: false
HealthCheck:
  Protocol: tcp
  Port: 6379
  Interval: 10
  Timeout: 5
  HealthyThreshold: 3
  UnhealthyThreshold: 3
Services:
  - preview-redis
